name: flutter_form_bloc
description: Create Beautiful Forms in Flutter. The easiest way to Prefill, Async Validation, Update Form Fields, and Show Progress, Failures or Navigate by Reacting to the Form State.
version: 0.31.0
homepage: https://github.com/GiancarloCode/form_bloc/tree/master/packages/flutter_form_bloc
repository: https://github.com/GiancarloCode/form_bloc/tree/master/packages/flutter_form_bloc
issue_tracker: https://github.com/GiancarloCode/form_bloc/issues

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: '>=9.0.0 <10.0.0'
  form_bloc:
    path: ../form_bloc
  equatable: ^2.0.5
  rxdart: '>=0.28.0 <0.29.0'
  flutter_keyboard_visibility: ^6.0.0
  collection: ^1.19.0
  intl: '>=0.20.0 <0.21.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
